# Generated by Django 3.0.4 on 2020-03-27 00:59

import R_projects.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20)),
                ('first_last_name', models.CharField(max_length=20)),
                ('second_last_name', models.CharField(blank=True, max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Group_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email_domains', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='R_projects.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('accounts', R_projects.models.IntegerRangeField()),
                ('activated_accounts', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Research_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='R_projects.Group_area')),
            ],
        ),
        migrations.CreateModel(
            name='Research_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=10)),
                ('areas', models.ManyToManyField(to='R_projects.Research_area')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='R_projects.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20)),
                ('first_last_name', models.CharField(max_length=20)),
                ('second_last_name', models.CharField(blank=True, max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('active', models.BooleanField(default=False)),
                ('projects', models.ManyToManyField(blank=True, to='R_projects.Project')),
                ('r_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='R_projects.Research_group')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='R_projects.Research_area'),
        ),
        migrations.AddField(
            model_name='project',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='R_projects.Director'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='R_projects.Project_type'),
        ),
        migrations.AddField(
            model_name='director',
            name='r_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='R_projects.Research_group'),
        ),
    ]
