# Generated by Django 3.0.4 on 2020-03-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='token',
            field=models.CharField(default=12345, max_length=30),
            preserve_default=False,
        ),
    ]
