# Generated by Django 3.0.4 on 2020-03-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_projects', '0003_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(to='R_projects.Project'),
        ),
    ]
