# Generated by Django 3.0.4 on 2020-03-27 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('R_projects', '0004_auto_20200327_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='R_projects.Project'),
        ),
    ]
