# Generated by Django 3.0.4 on 2020-04-03 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('R_projects', '0007_auto_20200402_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='financing',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='requirements',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='terms',
            field=models.BooleanField(default=False),
        ),
    ]
