# Generated by Django 3.0.4 on 2020-04-03 16:05

import R_projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_projects', '0008_auto_20200403_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='financing',
            field=R_projects.models.IntegerRangeField(),
        ),
    ]
