# Generated by Django 3.0.4 on 2020-04-13 01:33

import R_projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R_projects', '0009_auto_20200403_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='financing',
            field=R_projects.models.IntegerRangeField(default=0),
        ),
    ]
